title: Jianwen
description: My B.S. and Ph.D.research experience include analyzing data for solving optimization problems ranging from physics to economics. Now passionate about data science and cloud computing.
# Build settings
theme: jekyll-theme-minimal
email: jl147@iu.edu

