theme: jekyll-theme-minimal


footer-links:
  email:yaliallen@hotmail.con
  facebook:
  github: barryclark/jekyll-now
  linkedin:in/jianwen-liu-32541266
  rss: # just type anything here for a working RSS icon
  twitter: jekyllrb
